services:
  - type: web
    name: chat-app-server
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: CLIENT_URL
        sync: false
